theme: jekyll-theme-cayman

title: Tint Vogue
tagline: AI for Personal Color Analysis in Fashion/E-commerce
description: Tint Vogue adalah solusi inovatif berbasis Computer Vision dan Artificial Intelligence (AI) yang mengatasi permasalahan mendasar dalam pemilihan warna pakaian, yaitu ketidakakuratan persepsi visual manusia terhadap keserasian warna dengan biometric undertone kulit. Produk ini dikembangkan berdasarkan prinsip fisika interaksi cahaya dan optik pada kulit manusia. Dengan teknologi AI, Tint Vogue mampu melakukan ekstraksi presisi nilai heksadesimal warna kulit pengguna, lalu mencocokkannya secara akurat dengan database palet warna musiman (Spring, Summer, Autumn, Winter) yang harmonis.
